#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import http.cookiejar
import urllib.request

def build_opener_with_chrome_cookies(domain=None):
    cookiejar = http.cookiejar.CookieJar()    # No cookies stored yet
#由于要异机运行，以下值直接从chrome的开发者工具里面拷贝出来
    rows = [['PHPSESSID','3phh19s'],
['_fmdata','6C0053BBE7C0612CD0FF810887E8897FE747B83DC54FA8998AA47BABB11B6C63B838F925BBC38'],
['_ga','GA1.2.46321.1414723914'],
['rcount','47bf3d4466b0ae'],
['ruser','1940'],
['v2x4_48dd_auth','3860fF93vAP5fP%2Bl9BnvDHlT7kEwm0og'],
['v2x4_48dd_lastact','14609portal.php%09'],
['v2x4_48dd_lastcheckfeed','24952483'],
['v2x4_48dd_lastvisit','1499'],
['v2x4_48dd_lip','69258466'],
['v2x4_48dd_saltkey','nvS2y'],
['v2x4_48dd_seccode','32aa74173bad9'],
['v2x4_48dd_sid','P2PP'],
['v2x4_48dd_smile','1'],
['v2x4_48dd_ulastactivity','db75c4lwlzOsuoUE0wHlnZ']]
    for row in rows:
        cookie_item = http.cookiejar.Cookie(
            version=0, name=row[0], value=row[1],
                     port=None, port_specified=None,
                     domain='', domain_specified=None, domain_initial_dot=None,
                     path='', path_specified=None,
                     secure=None,
                     expires=None,
                     discard=None,
                     comment=None,
                     comment_url=None,
                     rest=None,
                     rfc2109=False,
            )
        cookiejar.set_cookie(cookie_item)    # Apply each cookie_item to cookiejar
    headers = ('User-Agent','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36')
    opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cookiejar))    # Return opener
    opener.addheaders=[headers]
    return opener

if __name__ == '__main__':
    opener = build_opener_with_chrome_cookies(domain='chiphell.com')
    #html_doc = opener.open('https://www.chiphell.com').read()
    html = opener.open('https://www.chiphell.com/').read()
    #html =str(html,'utf-8')
    html = str(html,'utf-8', errors='ignore')
    #print ( html )
    import re
    jf = re.search('class="showmenu"\>(积分: \d+)\</a\>',html,re.IGNORECASE).group(1)
    print (jf)
