#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import http.cookiejar
import urllib.request

def build_opener_with_chrome_cookies():
    cookiejar = http.cookiejar.CookieJar()    # No cookies stored yet
#由于要在服务器上cron，以下值直接从chrome的开发者工具里面拷贝出来
    rows = [['PHPSESSID','319s'],
['_fmdata','6CB11B6C63B838F925BBC38'],
['_ga','GA3914'],
['rcount','46b0ae'],
['ruser','1940'],
['v2x4_48dd_auth','386jhkjhkyuytuEwm0og'],
['v2x4_48dd_lastact','14609portal.php%09'],
['v2x4_48dd_lastcheckfeed','25276876483'],
['v2x4_48dd_lastvisit','1499'],
['v2x4_48dd_lip','69258466'],
['v2x4_48dd_saltkey','nvS2y'],
['v2x4_48dd_seccode','32aahjgfht73bad9'],
['v2x4_48dd_sid','P2PP'],
['v2x4_48dd_smile','1'],
['v2x4_48dd_ulastactivity','dbkjhkhj8768lnZ']]
    for row in rows:
        cookie_item = http.cookiejar.Cookie(
            version=0, name=row[0], value=row[1],
                     port=None, port_specified=None,
                     domain='', domain_specified=None, domain_initial_dot=None,
                     path='', path_specified=None,
                     secure=None,
                     expires=None,
                     discard=None,
                     comment=None,
                     comment_url=None,
                     rest=None,
                     rfc2109=False,
            )
        cookiejar.set_cookie(cookie_item)    # Apply each cookie_item to cookiejar
    headers = ('User-Agent','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36')
    opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cookiejar))    # Return opener
    opener.addheaders=[headers]
    return opener

if __name__ == '__main__':
    opener = build_opener_with_chrome_cookies()
    html = opener.open('https://www.chiphell.com/').read()
    html = str(html,'utf-8', errors='ignore')
    import re
    jf = re.search('class="showmenu"\>(积分: \d+)\</a\>',html,re.IGNORECASE).group(1)
    print (jf)
