#!/usr/bin/ruby
require 'net/http'
require 'mechanize'
require 'json'

data = Hash.new

agent = Mechanize.new
agent.user_agent_alias = 'Linux Firefox'
agent.request_headers = {'accept-language' => 'zh-CN',}

url = "https://api-otc.huobi.pro/v1/otc/base/market/price"
page = agent.get url
resp = JSON.parse(page.body)
usdtprice = resp['data'][2]['price'].to_f;
ethprice = resp['data'][1]['price'].to_f;
btcprice = resp['data'][0]['price'].to_f;

data["price"] = Hash.new
data["price"]["usdt"] = usdtprice
data["price"]["btc"] = btcprice
data["price"]["eth"] = ethprice

url = "https://api-otc.huobi.pro/v1/otc/trade/list/public?coinId=2&tradeType=1&currentPage=1&payWay=&country="
page = agent.get url
resp = JSON.parse(page.body)

premium = (resp['data'][0]['price'] / usdtprice) * 100
data["usdt"] = Hash.new
data['usdt']['premium'] = (premium - 100 ).round(2)
data['usdt']['data'] = Array.new

i = 0
resp['data'][0..2].each do |price_info|
    data['usdt']['data'][i] = Hash.new
    data['usdt']['data'][i]['username'] = price_info['userName']
    data['usdt']['data'][i]['pay_method'] = price_info['payMethod']
    data['usdt']['data'][i]['price'] = price_info['price']
    data['usdt']['data'][i]['min_limit'] = price_info['minTradeLimit']
    data['usdt']['data'][i]['max_limit'] = price_info['maxTradeLimit']

    i += 1
end

url = "https://api-otc.huobi.pro/v1/otc/trade/list/public?coinId=3&tradeType=1&currentPage=1&payWay=&country=&merchant=1&online=1&range=0"
page = agent.get url
resp = JSON.parse(page.body)

data["eth"] = Hash.new
premium = (resp['data'][0]['price'] / ethprice) * 100
data['eth']['premium'] = (premium - 100).round(2)
data['eth']['data'] = Array.new

i = 0
resp['data'][0..2].each do |price_info|
    data['eth']['data'][i] = Hash.new
    data['eth']['data'][i]['username'] = price_info['userName']
    data['eth']['data'][i]['pay_method'] = price_info['payMethod']
    data['eth']['data'][i]['price'] = price_info['price']
    data['eth']['data'][i]['pay_limit'] = "#{price_info['minTradeLimit']} - #{price_info['maxTradeLimit']}"
    i += 1
end

url = "https://api-otc.huobi.pro/v1/otc/trade/list/public?coinId=1&tradeType=1&currentPage=1&payWay=&country=&merchant=1&online=1&range=0"
page = agent.get url
resp = JSON.parse(page.body)

data["btc"] = Hash.new
premium = ((resp['data'][0]['price'] / btcprice) * 100 - 100).round(2)
data['btc']['premium'] = premium
data['btc']['data'] = Array.new

i = 0
resp['data'][0..2].each do |price_info|
    data['btc']['data'][i] = Hash.new
    data['btc']['data'][i]['username'] = price_info['userName']
    data['btc']['data'][i]['pay_method'] = price_info['payMethod']
    data['btc']['data'][i]['price'] = price_info['price']
    data['btc']['data'][i]['pay_limit'] = "#{price_info['minTradeLimit']} - #{price_info['maxTradeLimit']}"
    i += 1
end

url = "https://bittrex.com/api/v1.1/public/getmarketsummary?market=btc-lmc"
page = agent.get url
resp = JSON.parse(page.body)
data['lmc'] = Hash.new
data['lmc']['last'] = (resp['result'][0]['Last'] * 100000000).to_i
data['lmc']['high'] = (resp['result'][0]['High'] * 100000000).to_i
data['lmc']['low'] = (resp['result'][0]['Low'] * 100000000).to_i

data['time'] = Time.now.to_s.split(' ')[0..1].join(' ')

puts data.to_json
