#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sqlite3
import sys
for arg in sys.argv[1:]:
    conn = sqlite3.connect(arg)
    cursor = conn.cursor()
    cursor.execute("select name from sqlite_master where type='table' order by name")
    tbs = cursor.fetchall()
    for t in tbs:
        cursor.execute("SELECT COUNT(*) FROM %s"%(t))
        count = cursor.fetchall()
        tbname = "表名 : %s " % t
        print ( "%s记录数 : %d" % ( tbname ,count[0][0] ) )
        print ( "{0:2} {1:27} {2:25} {3:12} {4:8}".format('序号','字段名','类型','NULL/缺省值','是否主键' ) )
        cursor.execute("PRAGMA table_info(%s)"%(t))
        for tbinfo in cursor.fetchall():
            print ( "{0:4} {1:30} {2:16} {3:12} {4:4} {5:10}".format( tbinfo[0],str(tbinfo[1]),tbinfo[2],tbinfo[3],str(tbinfo[4]),tbinfo[5] ) )
    cursor.close()
    conn.close()
